name = "mamoochi"
pages_build_output_dir = "dist"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"                                       # available in your Worker on env.DB
database_name = "inbox"
database_id = "9a4c5463-2684-4973-8a04-6c3f5886924c"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "inboxKV"
id = "641b2dd1ff024c6d88da451bee969e54"

[vars]
NUXT_SESSION_PASSWORD="092f2092169e44339f73c32e44fa7497"
NUXT_PUBLIC_SITE_NAME_FA ='مَموچی'
NUXT_PUBLIC_TITLE_FA ='مَـ موچیــ'
NUXT_PUBLIC_DESCRIPTION_FA ="کوچولو و بازیگوش"
NUXT_PUBLIC_SITE_NAME_EN ='Mamoochi'
NUXT_PUBLIC_TITLE_EN ='Ma moochi'
NUXT_PUBLIC_DESCRIPTION_EN ='Tiny & Playful'
